# These are supported funding model platforms
patreon: EliteSoftware Company - https://patreon.com/EliteSoftwareCo?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
